Add some behat functions
alexandresalome/mailcatcher pull request #34
Opened 2019-04-17 16:34 UTC by mauriau

2019-11-24 12:45 UTC, alexandresalome requested changes
First of all, thank you for your contribution! Having more sentences is a great improvement the library.

I'm sorry for the delay, I abandoned the project some times, but hey! I'm back!

I've fixed automated tests, we should be able to continuously improve it properly now.

I've made some request for changes, I let you see and tell me if you have time for it.

And I forgot to mention:

- Update README with new steps you created
- Update CHANGELOG with details of the change

2019-11-24 12:45 UTC, alexandresalome commented on .gitignore
> +.idea/
This should be in your personal `.gitignore`, not in project's one.

2019-11-24 12:45 UTC, alexandresalome commented on Behat/MailCatcherContext.php
> +     * @Then /^I should not see mail containing "([^"]+)"$/
You can use the new Behat syntax `:text` here too.

2019-11-24 12:45 UTC, alexandresalome commented on Behat/MailCatcherContext.php
>       * @Then /^I should see mail containing "([^"]+)"$/
To migrate to new Behat syntax, too.

2019-11-24 12:45 UTC, alexandresalome commented on Behat/MailCatcherContext.php
> +     * @Then /^I should not see mail to "([^"]+)"$/
Please use new Behat syntax.

2019-11-24 12:45 UTC, alexandresalome commented on Behat/MailCatcherContext.php
>       * @Then /^I should see mail to "([^"]+)"$/
Please use new Behat syntax.

2019-11-24 12:45 UTC, alexandresalome commented on Behat/MailCatcherContext.php
> +     * @Then /^I should not see mail with subject "([^"]+)"$/
Please use new Behat syntax.

2019-11-24 12:45 UTC, alexandresalome commented on Behat/MailCatcherContext.php
> +     * @When I open mail with subject :subject from :from to :to
We need tests for new sentences.

2019-11-24 12:45 UTC, alexandresalome commented on Behat/MailCatcherContext.php
> +     * @Then /^I should not see mail containing "([^"]+)"$/
We need tests for new sentences.

2019-11-24 12:45 UTC, alexandresalome commented on Behat/MailCatcherContext.php
> +    protected function findMail($type, $value, $negation = false)
This implementation of negation is complex.

I'd recommend a separated method for this purpose, to keep code simple:

```php
protected function findNoMail($type, $value)
{
    try {
		$this->findMail($type, $value);
    } catch (\InvalidArgumentException $e) {
        // Mail not found is OK
        return;
    }

	throw new \InvalidArgumentException(sprintf('A message corresponding to your criterias was found: "%s".', json_encode($criterias)));
}
```

2019-11-24 12:45 UTC, alexandresalome commented on Behat/MailCatcherTrait.php
> +            }
Same as above.

2025-02-22 17:01 UTC, AlexandreCavanna commented
Hello @alexandresalome,

I confirm that you can close this pull request. The employee who created it is no longer with our company and we are in the process of removing Behat from our tech stack anyway.

Thanks a lot for taking care of this!

2025-03-03 12:14 UTC, closed without merging